### ISSUE TITLE
Can we make the dialog draggable or place it left bottom corner below watchlist

### ISSUE THREAD

**Issue by rahulmr** [Rahulghuge94/scalp_it#1]
Can we make the dialog draggable or place it left bottom corner below watchlist

Also add options for strike price could be good

BTW excellent extension. But it is not shown as popup but is integrated in UI

**Comment by Rahulghuge94** [comment]
Yes we can make it dragable. I will add it in evening. please do contribute there are lot of feature needs to be added.
